import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faFlag as fasFlag,
  faPhone as fasPhone,
  faCloudArrowUp as fasCloudArrowUp,
  faBell as fasBell,
  faUser as fasUser,
  faDesktop as fasDesktop,
  faLink as fasLink,
  faGear as fasGear,
  faRocket as fasRocket,
  faCarSide as fasCarSide,
  faRightFromBracket as fasRightFromBracket,
  faClone as fasClone,
  faFiles as fasFiles,
  faStar as fasStar,
  faFile as fasFile,
  faTable as fasTable,
  faPlus as fasPlus,
  faEllipsis as fasEllipsis,
  faUpload as fasUpload,
  faCopy as fasCopy,
  faTerminal as fasTerminal,
  faRightToBracket as fasRightToBracket,
  faShareNodes as fasShareNodes,
  faHashtag as fasHashtag,
  faEdit as fasEdit,
  faPlug as fasPlug,
  faTrash as fasTrash,
  faRecycle as fasRecycle,
  faBoxArchive as fasBoxArchive,
  faTrashCan as fasTrashCan
} from '@fortawesome/pro-solid-svg-icons'
import {
  faTrash as farTrash,
  faTrashCan as farTrashCan,
  faFlag as farFlag,
  faStar as farStar,
  faPlus as farPlus,
  faFolderPlus as farFolderPlus,
  faShareNodes as farShareNodes,
  faSquareCaretDown as farSquareCaretDown,
  faEdit as farEdit,
  faArrowDownToBracket as farArrowDownToBracket,
  faBell as farBell,
  faUser as farUser,
  faEllipsis as farEllipsis,
  faCircleInfo as farCircleInfo,
  faHashtag as farHashtag,
  faArrowLeft as farArrowLeft,
  faRectangleHistory as farRectangleHistory,
  faSort as farSort,
  faRectangleVerticalHistory as farRectangleVerticalHistory,
  faBoxArchive as farBoxArchive,
  faRobot as farRobot,
  faPlug as farPlug,
  faDatabase as farDatabase,
  faFiles as farFiles,
  faCloudArrowUp as farCloudArrowUp,
  faTable as farTable,
  faGoalNet as farGoalNet,
  faFileAlt as farFileAlt,
  faFolderClosed as farFolderClosed
} from '@fortawesome/pro-regular-svg-icons'

import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

export function useFontAwesome() {
  library.add(
    farFolderClosed,
    farFileAlt,
    farGoalNet,
    farTable,
    farCloudArrowUp,
    farFiles,
    farDatabase,
    farPlug,
    farRobot,
    farBoxArchive,
    farRectangleVerticalHistory,
    farTrashCan,
    farTrash,
    farSort,
    farRectangleHistory,
    farArrowLeft,
    farHashtag,
    farCircleInfo,
    farEllipsis,
    farUser,
    farBell,
    farArrowDownToBracket,
    fasFiles,
    farSquareCaretDown,
    farShareNodes,
    farFolderPlus,
    farEdit,
    farPlus,
    fasTrashCan,
    fasBoxArchive,
    fasRecycle,
    fasFlag,
    farFlag,
    fasPhone,
    fasCloudArrowUp,
    fasBell,
    fasUser,
    fasDesktop,
    fasLink,
    fasGear,
    fasRocket,
    fasCarSide,
    fasRightFromBracket,
    fasClone,
    fasStar,
    fasFile,
    fasTable,
    fasPlus,
    fasEllipsis,
    fasUpload,
    fasCopy,
    fasTerminal,
    fasRightToBracket,
    fasShareNodes,
    fasHashtag,
    farStar,
    fasEdit,
    fasPlug,
    fasTrash
  )
  return FontAwesomeIcon
}
